#!/usr/bin/env python3
"""No stray CJK developer text in PocketClaw-owned source.

Scans every tracked text file for CJK characters. Each file that contains any
must match an allowlist entry, and every entry says why the text is there:

  localization   user-facing translations, language endonyms, and the tests
                 that assert them
  upstream       vendored PicoClaw material PocketClaw does not own, or CJK
                 that is functional input handling rather than prose
  fixture        test data that exercises CJK handling on purpose

A file entry pins the number of CJK lines it may contain, so a translated
string table cannot quietly accumulate a developer comment. A directory or
generated-file entry has no count: its content is owned elsewhere.

Unicode in general is not banned -- Arabic, Hindi and accented text are
ordinary localization. The check exists because stray Chinese developer
comments were found in PocketClaw's own Kotlin and Dart and cleaned out.

Exit status is 0 when every CJK-bearing file is classified and within its
count, and 1 otherwise.
"""

from __future__ import annotations

import fnmatch
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

CJK = re.compile(
    "[\u3000-\u303f\u3040-\u30ff\u3100-\u312f\u3130-\u318f\u31a0-\u31ff"
    "\u3400-\u4dbf\u4e00-\u9fff\uac00-\ud7af\uf900-\ufaff\uff00-\uffef]"
)

VALID_CATEGORIES = {"localization", "upstream", "fixture"}

# (glob, category, lines or None, reason)
ALLOWLIST = [
    # --- localization ---
    ("lib/l10n/app_*.arb", "localization", None,
     "Flutter translation tables; the ja/ko/zh ones are CJK by nature"),
    ("lib/src/generated/l10n/app_localizations_*.dart", "localization", None,
     "generated by flutter gen-l10n from the ARB files"),
    ("lib/src/ui/config_page.dart", "localization", 3,
     "language endonyms in the language picker"),
    ("core/src/web/frontend/src/i18n/locales/*.json", "localization", None,
     "dashboard translation tables"),
    ("core/src/web/frontend/src/i18n/languages.ts", "localization", 3,
     "dashboard language endonyms"),
    ("core/src/web/backend/i18n.go", "localization", 12,
     "Chinese strings for the desktop tray menu"),
    ("test/widgets/settings_localization_test.dart", "localization", 9,
     "asserts translated Settings strings"),
    ("test/widgets/models_settings_card_test.dart", "localization", 3,
     "asserts translated Models strings"),
    ("core/src/web/frontend/src/components/language-menu.test.tsx", "localization", 8,
     "asserts the endonyms in the language menu"),
    ("core/src/web/frontend/src/i18n/i18n.test.ts", "localization", 14,
     "asserts translated dashboard strings"),
    ("core/src/web/frontend/src/i18n/routes.i18n.test.tsx", "localization", 5,
     "asserts translated route strings, including the zh term for gateway"),
    ("CHANGELOG_DEV.md", "localization", 1,
     "quotes the zh UI label a change aligned with"),
    # --- upstream ---
    ("core/src/docs/*", "upstream", None, "PicoClaw's translated documentation"),
    ("core/src/**/README.zh.md", "upstream", None, "PicoClaw's Chinese package READMEs"),
    ("core/src/README.md", "upstream", 1, "PicoClaw's links to its translated READMEs"),
    ("core/src/.env.example", "upstream", 1, "PicoClaw's Feishu example label"),
    ("core/src/workspace/skills/weather/SKILL.md", "upstream", 1,
     "a geocoding example for a Chinese city name"),
    ("core/src/cmd/membench/llm_client.go", "upstream", 2,
     "a PicoClaw developer benchmark, not shipped"),
    ("core/pocketclaw-core-v0.3.1.patch", "upstream", None,
     "generated diff against PicoClaw; mirrors the vendored files"),
    ("core/src/pkg/audio/sentence.go", "upstream", 3,
     "sentence splitting on CJK full stops, question and exclamation marks"),
    ("core/src/pkg/channels/qq/qq.go", "upstream", 2,
     "QQ URL sanitising with the ideographic full stop"),
    ("core/src/pkg/config/config_struct.go", "upstream", 3,
     "list parsing that accepts the fullwidth comma"),
    ("core/src/pkg/evolution/skill_draft_policy.go", "upstream", 2,
     "summary truncation on CJK punctuation"),
    ("core/src/pkg/tools/integration/web.go", "upstream", 4,
     "Sogou date-range query terms, sent to the search engine"),
    # --- fixture ---
    ("core/src/pkg/tools/integration/web_test.go", "fixture", 9,
     "asserts the Sogou date-range query terms"),
    ("core/src/pkg/channels/qq/qq_test.go", "fixture", 1, "QQ URL sanitising"),
    ("core/src/pkg/config/config_test.go", "fixture", 5, "fullwidth-comma list parsing"),
    ("core/src/pkg/evolution/*_test.go", "fixture", None,
     "skill evolution over Chinese task summaries"),
    ("core/src/pkg/seahorse/*_test.go", "fixture", None, "full-text search over CJK text"),
    ("core/src/pkg/tools/result_budget_test.go", "fixture", 2,
     "byte-budget truncation must not split a CJK rune"),
    ("core/src/web/backend/api/config_test.go", "fixture", 4,
     "allow-list parsing with fullwidth commas"),
    ("test/unit/plain_text_log_sanitizer_test.dart", "fixture", 1,
     "the sanitizer must keep non-Latin text"),
]


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=REPO, capture_output=True,
                         check=True).stdout
    return [name for name in out.decode().split("\0") if name]


def cjk_line_count(path: Path) -> int:
    try:
        data = path.read_bytes()
    except OSError:
        return 0
    if b"\0" in data[:8192]:
        return 0
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return 0
    return sum(1 for line in text.splitlines() if CJK.search(line))


def entry_for(name: str):
    for entry in ALLOWLIST:
        glob = entry[0]
        if fnmatch.fnmatchcase(name, glob) or (
            glob.endswith("/*") and name.startswith(glob[:-1])
        ):
            return entry
    return None


def scan() -> list[str]:
    problems = []
    for name in tracked_files():
        lines = cjk_line_count(REPO / name)
        if not lines:
            continue
        entry = entry_for(name)
        if entry is None:
            problems.append(f"{name}: {lines} CJK line(s), not classified")
            continue
        expected = entry[2]
        if expected is not None and lines != expected:
            problems.append(
                f"{name}: {lines} CJK line(s), allowlisted for {expected} "
                f"({entry[1]}: {entry[3]})"
            )
    return problems


def main() -> int:
    problems = scan()
    for problem in problems:
        print(problem)
    if problems:
        print(f"FAIL {len(problems)} unclassified or changed CJK occurrence(s)")
        return 1
    print("PASS no unclassified CJK text in tracked files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
