#!/usr/bin/env python3
"""Renders the user-facing release notes from the app's own What's New source.

PC-DEF-064. The What's New screen and the GitHub release notes were two
independent pieces of prose, so the app could describe a release the notes did
not, and neither was wrong on its own terms. There is one source now: the
release structure in lib/src/whats_new/whats_new_release.dart decides which
bullets exist and in what order, and lib/l10n/app_en.arb holds their words.

This renders that source to Markdown. `--check` re-renders and compares, which
is what the release gate runs: drift fails rather than being discovered when
someone reads the published notes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RELEASE_DART = REPO_ROOT / "lib/src/whats_new/whats_new_release.dart"
ARB_EN = REPO_ROOT / "lib/l10n/app_en.arb"
NOTES = REPO_ROOT / "docs/RELEASE_NOTES.md"

SECTION_TITLES = {
    "added": "New",
    "improved": "Improvements",
    "fixed": "Fixes",
}


def current_release_source(dart_source: str) -> str:
    """Narrows the source to the one release the app actually renders.

    The file keeps each shipped release and names the live one through
    currentWhatsNewRelease. Parsing the whole file would concatenate two
    releases into a single set of notes -- two "Fixes" headings, and a patch
    release described with the previous release's bullets.
    """
    named = re.search(r"currentWhatsNewRelease\s*=\s*(\w+)\s*;", dart_source)
    if not named:
        raise SystemExit("release notes: no currentWhatsNewRelease in whats_new_release.dart")
    opening = re.search(
        rf"final WhatsNewRelease {named.group(1)}\s*=\s*WhatsNewRelease\(",
        dart_source,
    )
    if not opening:
        raise SystemExit(
            f"release notes: {named.group(1)} is not defined in whats_new_release.dart"
        )
    depth = 0
    for index in range(opening.end() - 1, len(dart_source)):
        if dart_source[index] == "(":
            depth += 1
        elif dart_source[index] == ")":
            depth -= 1
            if depth == 0:
                return dart_source[opening.start():index + 1]
    raise SystemExit("release notes: unterminated WhatsNewRelease literal")


def parse_release(dart_source: str) -> tuple[str, list[tuple[str, list[str]]]]:
    """Reads the version and the ordered bullet keys per section.

    Parsed rather than duplicated: a bullet added to the Dart list but not here
    would be exactly the drift this exists to prevent.
    """
    dart_source = current_release_source(dart_source)
    version = re.search(r"version:\s*'([^']+)'", dart_source)
    if not version:
        raise SystemExit("release notes: no version in whats_new_release.dart")

    sections: list[tuple[str, list[str]]] = []
    for kind, body in re.findall(
        r"kind:\s*WhatsNewSectionKind\.(\w+),\s*bullets:\s*\[(.*?)\]",
        dart_source,
        re.DOTALL,
    ):
        keys = re.findall(r"l10n\.(\w+)", body)
        sections.append((kind, keys))
    if not sections:
        raise SystemExit("release notes: no sections in whats_new_release.dart")
    return version.group(1), sections


def render(version: str, sections: list[tuple[str, list[str]]],
           strings: dict[str, str]) -> str:
    lines = [
        "<!-- Generated by tool/release_notes.py. Do not edit by hand:",
        "     the source is lib/src/whats_new/whats_new_release.dart and",
        "     lib/l10n/app_en.arb, which are what the app itself renders. -->",
        "",
        f"# PocketClaw {version}",
        "",
    ]
    for kind, keys in sections:
        title = SECTION_TITLES.get(kind, kind.title())
        lines.append(f"## {title}")
        lines.append("")
        for key in keys:
            if key not in strings:
                raise SystemExit(f"release notes: {key} is missing from app_en.arb")
            lines.append(f"- {strings[key]}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the rendered notes differ from the committed file",
    )
    args = parser.parse_args()

    version, sections = parse_release(RELEASE_DART.read_text(encoding="utf-8"))
    strings = json.loads(ARB_EN.read_text(encoding="utf-8"))
    rendered = render(version, sections, strings)

    if not args.check:
        NOTES.write_text(rendered, encoding="utf-8")
        print(f"wrote {NOTES.relative_to(REPO_ROOT)} for {version}")
        return 0

    if not NOTES.exists():
        print(f"FAIL {NOTES.relative_to(REPO_ROOT)} is missing", file=sys.stderr)
        return 1
    if NOTES.read_text(encoding="utf-8") != rendered:
        print(
            "FAIL the release notes no longer match the app's What's New source.\n"
            "     Run: python3 tool/release_notes.py",
            file=sys.stderr,
        )
        return 1
    bullets = sum(len(keys) for _, keys in sections)
    print(f"PASS release notes match What's New ({version}, {bullets} bullets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
