// Package coresource fingerprints the source that produces the Core binary.
//
// The Core is a committed artifact: android/app/src/main/jniLibs/arm64-v8a/
// libpicoclaw.so is checked in, and the Gradle build packages whatever is
// staged there. Nothing in the Flutter or Gradle build compiles Go, so an edit
// under core/src changes a device's behaviour only after
// core/build-android-arm64.sh is re-run.
//
// The catalog guard catches one shape of that mistake: a Core built before the
// current manifest.json. It cannot catch a Go-only change, because a Core built
// yesterday still embeds today's catalog when manifest.json did not move. That
// is the gap this package closes. The canonical build stamps the fingerprint
// into the binary; the test gate recomputes it from the working tree and
// compares.
package coresource

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// RebuildInstruction is the one action that resolves a stale Core.
const RebuildInstruction = "./core/build-android-arm64.sh"

// includedRoots are the parts of core/src that the Core binary is built from.
//
// Go compiles only what ./cmd/picoclaw reaches, and everything it reaches lives
// in cmd/, pkg/ or at the module root; workspace/ is embedded from the module
// root. web/ builds the separate launcher binary
// and the Core imports none of it; docs/, docker/, examples/, integration/ and
// scripts/ reach the compiler not at all. Naming the inputs rather than
// excluding non-inputs keeps a new directory out of the fingerprint until
// someone decides it belongs there, which is the safe direction: a spurious
// rebuild prompt is cheap, a blind spot is what shipped the stale Core.
var includedRoots = []string{"cmd", "pkg", "workspace"}

// rootFiles are the module-level inputs: the embed at the module root, the
// dependency pins, and the Makefile that fixes the build tags and flags.
var rootFiles = []string{"go.mod", "go.sum", "Makefile"}

// skippedDirs never contribute. cmd/*/workspace is generated by `make
// generate` from the tracked workspace/ tree, so hashing it would fold a build
// output back into the fingerprint of its own inputs.
var skippedDirs = map[string]struct{}{
	".git": {}, "node_modules": {}, "testdata": {}, "workspace": {},
}

// embeddedFiles are the non-Go files compiled into the Core, named one by one.
//
// A wildcard over *.json was the obvious first shape and the wrong one: tests
// write JSON beside the packages they exercise, so the fingerprint moved while
// the gate that reads it was still running. Naming the inputs makes the value
// depend only on files a build consumes. What keeps the list honest is
// TestEveryEmbeddedAssetIsAFingerprintInput, which reads the //go:embed
// directives out of the Core's own source and fails if one names something this
// does not cover.
var embeddedFiles = map[string]struct{}{
	"pkg/pcruntime/manifest.json": {},
}

// Fingerprint is a deterministic digest of the Core's build inputs under root,
// which is a core/src directory.
//
// It is content-addressed: only relative paths and file bytes take part, so two
// clean checkouts of the same source produce the same value. Nothing that
// varies between machines or between builds of identical source — a timestamp,
// an mtime, an absolute path, a username, a random build id — is allowed near
// it, because a fingerprint that changes on its own cannot say anything about
// staleness.
func Fingerprint(root string) (string, error) {
	files, err := collect(root)
	if err != nil {
		return "", err
	}
	if len(files) == 0 {
		return "", fmt.Errorf("no Core source found under %s", root)
	}

	paths := make([]string, 0, len(files))
	for relative := range files {
		paths = append(paths, relative)
	}
	sort.Strings(paths)

	digest := sha256.New()
	for _, relative := range paths {
		fmt.Fprintf(digest, "%s\x00%s\n", relative, files[relative])
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

func collect(root string) (map[string]string, error) {
	files := make(map[string]string, 1024)

	for _, name := range rootFiles {
		sum, err := hashFile(filepath.Join(root, name))
		if err != nil {
			return nil, err
		}
		files[name] = sum
	}

	for _, top := range includedRoots {
		base := filepath.Join(root, top)
		if _, err := os.Stat(base); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		err := filepath.WalkDir(base, func(fullPath string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			relative, relErr := filepath.Rel(root, fullPath)
			if relErr != nil {
				return relErr
			}
			// Slash-separated so the fingerprint does not depend on the host's
			// path separator.
			relative = filepath.ToSlash(relative)

			if entry.IsDir() {
				if _, skipped := skippedDirs[entry.Name()]; skipped && relative != top {
					return fs.SkipDir
				}
				return nil
			}
			if !covers(relative) {
				return nil
			}
			sum, hashErr := hashFile(fullPath)
			if hashErr != nil {
				return hashErr
			}
			files[relative] = sum
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return files, nil
}

// covers reports whether one file, named relative to core/src, changes the
// compiled Core.
//
// workspace/ is embedded byte for byte, so every file in it counts. Elsewhere
// only Go source the compiler sees and the named embedded assets do; _test.go
// files are excluded deliberately, because a test edit does not change the
// shipped binary and demanding a Core rebuild for one would train people to
// ignore the guard.
func covers(relative string) bool {
	if relative == "workspace" || strings.HasPrefix(relative, "workspace/") {
		return true
	}
	for _, name := range rootFiles {
		if relative == name {
			return true
		}
	}
	if _, embedded := embeddedFiles[relative]; embedded {
		return true
	}
	name := path.Base(relative)
	return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
}

func hashFile(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	digest := sha256.New()
	if _, err := io.Copy(digest, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

// Stamped is the fingerprint of the Core source this binary was built from.
//
// It is set at link time by the canonical build:
//
//	-X github.com/sipeed/picoclaw/pkg/coresource.Stamped=<fingerprint>
//
// An empty value means the binary was not built through
// core/build-android-arm64.sh, which is itself worth knowing: the test gate
// treats an unstamped Core exactly like a stale one, because neither can be
// shown to match the source in the working tree.
var Stamped string

// Describe names the Core source this binary was built from, for the startup
// diagnostics. It also keeps Stamped referenced by live code: the linker drops
// an unused variable, and a dropped variable takes the -X value with it.
func Describe() string {
	if Stamped == "" {
		return "unstamped"
	}
	return Stamped
}

// StagedCoreMatches reports whether a built Core carries fingerprint.
//
// The fingerprint is a plain string in the binary's data, so containment is the
// whole check: a Core built from this source has it, and one built from any
// other source, or built outside the canonical script, does not.
func StagedCoreMatches(core []byte, fingerprint string) bool {
	if len(fingerprint) != 64 {
		return false
	}
	return bytes.Contains(core, []byte(fingerprint))
}
