// Package coresource fingerprints the source that produces the Core binary.
//
// The Core is a committed artifact: android/app/src/main/jniLibs/arm64-v8a/
// libpocketclaw.so is checked in, and the Gradle build packages whatever is
// staged there. Nothing in the Flutter or Gradle build compiles Go, so an edit
// under core/src changes a device's behaviour only after
// core/build-android-arm64.sh is re-run.
//
// The catalog guard catches one shape of that mistake: a Core built before the
// current manifest.json. It cannot catch a Go-only change, because a Core built
// yesterday still embeds today's catalog when manifest.json did not move. That
// is the gap this package closes. The canonical build stamps the fingerprint
// into the binary; the test gate recomputes it from the working tree and
// compares.
package coresource

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// RebuildInstruction is the one action that resolves a stale Core.
const RebuildInstruction = "./core/build-android-arm64.sh"

// StagedCoreBinaries are the native binaries the canonical build stages, both
// of which ship inside the APK and both of which this fingerprint speaks for.
//
// libpocketclaw.so is the Core gateway, built from ./cmd/picoclaw.
// libpocketclaw-web.so is the dashboard, built from ./web/backend. They are
// one provenance unit: the canonical build stamps a single fingerprint into
// both, so a freshness check that reads only the first can pass while the
// dashboard on the device is from other source.
var StagedCoreBinaries = []string{"libpocketclaw.so", "libpocketclaw-web.so"}

// includedRoots are the parts of core/src that the shipped binaries are built
// from.
//
// The canonical build stages *two* native binaries and this fingerprint speaks
// for both. libpocketclaw.so is ./cmd/picoclaw, which reaches only cmd/, pkg/
// and the module root, with workspace/ embedded from the module root.
// libpocketclaw-web.so is ./web/backend — the dashboard — and it embeds the
// frontend bundle, so web/ is a build input in its own right.
//
// web/ was excluded until N4K-A on the true but insufficient ground that the
// Core imports none of it. It does not have to: it is separately compiled and
// separately shipped. N4J changed dashboard auth middleware, moved no
// fingerprint, and left a stale dashboard binary that nothing would report.
//
// docs/, docker/, examples/, integration/ and scripts/ reach neither compiler.
// Naming the inputs rather than excluding non-inputs keeps a new directory out
// of the fingerprint until someone decides it belongs there, which is the safe
// direction: a spurious rebuild prompt is cheap, a blind spot is what shipped
// the stale Core.
var includedRoots = []string{"cmd", "pkg", "workspace", "web"}

// rootFiles are the module-level inputs: the embed at the module root, the
// dependency pins, and the Makefile that fixes the build tags and flags.
var rootFiles = []string{"go.mod", "go.sum", "Makefile"}

// skippedDirs never contribute. cmd/*/workspace is generated by `make
// generate` from the tracked workspace/ tree, so hashing it would fold a build
// output back into the fingerprint of its own inputs.
//
// web/backend/dist is the same shape and the reason dist is here: it is the
// compiled frontend bundle, produced by `pnpm build:backend` from
// web/frontend/ and untracked apart from a .gitkeep. Hashing it would fold a
// build output into the fingerprint of its own inputs and, worse, make the
// value depend on whether the builder had run pnpm — a fingerprint that two
// clean checkouts disagree on says nothing at all. The bundle is covered
// through the frontend sources that produce it.
var skippedDirs = map[string]struct{}{
	".git": {}, "node_modules": {}, "testdata": {}, "workspace": {}, "dist": {},
}

// embeddedFiles are the non-Go files compiled into the Core, named one by one.
//
// A wildcard over *.json was the obvious first shape and the wrong one: tests
// write JSON beside the packages they exercise, so the fingerprint moved while
// the gate that reads it was still running. Naming the inputs makes the value
// depend only on files a build consumes. What keeps the list honest is
// TestEveryEmbeddedAssetIsAFingerprintInput, which reads the //go:embed
// directives out of the Core's own source and fails if one names something this
// does not cover.
var embeddedFiles = map[string]struct{}{
	"pkg/pcruntime/manifest.json": {},
}

// Fingerprint is a deterministic digest of the Core's build inputs under root,
// which is a core/src directory.
//
// It is content-addressed: only relative paths and file bytes take part, so two
// clean checkouts of the same source produce the same value. Nothing that
// varies between machines or between builds of identical source — a timestamp,
// an mtime, an absolute path, a username, a random build id — is allowed near
// it, because a fingerprint that changes on its own cannot say anything about
// staleness.
func Fingerprint(root string) (string, error) {
	files, err := collect(root)
	if err != nil {
		return "", err
	}
	if len(files) == 0 {
		return "", fmt.Errorf("no Core source found under %s", root)
	}

	paths := make([]string, 0, len(files))
	for relative := range files {
		paths = append(paths, relative)
	}
	sort.Strings(paths)

	digest := sha256.New()
	for _, relative := range paths {
		fmt.Fprintf(digest, "%s\x00%s\n", relative, files[relative])
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

func collect(root string) (map[string]string, error) {
	files := make(map[string]string, 1024)

	for _, name := range rootFiles {
		sum, err := hashFile(filepath.Join(root, name))
		if err != nil {
			return nil, err
		}
		files[name] = sum
	}

	for _, top := range includedRoots {
		base := filepath.Join(root, top)
		if _, err := os.Stat(base); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		err := filepath.WalkDir(base, func(fullPath string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			relative, relErr := filepath.Rel(root, fullPath)
			if relErr != nil {
				return relErr
			}
			// Slash-separated so the fingerprint does not depend on the host's
			// path separator.
			relative = filepath.ToSlash(relative)

			if entry.IsDir() {
				if _, skipped := skippedDirs[entry.Name()]; skipped && relative != top {
					return fs.SkipDir
				}
				return nil
			}
			if !covers(relative) {
				return nil
			}
			sum, hashErr := hashFile(fullPath)
			if hashErr != nil {
				return hashErr
			}
			files[relative] = sum
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return files, nil
}

// covers reports whether one file, named relative to core/src, changes either
// shipped binary.
//
// workspace/ is embedded byte for byte, so every file in it counts. web/ is its
// own rule, below. Elsewhere only Go source the compiler sees and the named
// embedded assets do; _test.go files are excluded deliberately, because a test
// edit does not change the shipped binary and demanding a rebuild for one would
// train people to ignore the guard.
func covers(relative string) bool {
	if relative == "workspace" || strings.HasPrefix(relative, "workspace/") {
		return true
	}
	if relative == "web" || strings.HasPrefix(relative, "web/") {
		return coversWebInput(relative)
	}
	for _, name := range rootFiles {
		if relative == name {
			return true
		}
	}
	if _, embedded := embeddedFiles[relative]; embedded {
		return true
	}
	name := path.Base(relative)
	return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
}

// coversWebInput reports whether one file under web/ changes
// libpocketclaw-web.so.
//
// Everything tracked under web/ counts except tests and the generated bundle.
// That is deliberately coarser than the rule for the Core, and it is the right
// direction here: the dashboard binary is a Go program that embeds the output
// of a TypeScript build, so its input set is the whole frontend toolchain —
// sources, index.html, the Vite and TypeScript configuration, package.json and
// the lockfile that pin what gets compiled in. Enumerating exactly which of
// those can alter the emitted bundle means re-deriving Vite's behaviour by
// hand and being wrong quietly. An over-broad rule costs an occasional
// unnecessary rebuild; an under-broad one is what N4J walked into.
//
// The two exclusions are the ones that would make the value wrong rather than
// merely conservative:
//
//   - dist/ is the bundle itself. skippedDirs prunes it during the walk; this
//     says so again for callers that ask about a path directly, so the two
//     cannot disagree.
//   - tests never reach either binary. Go tests are *_test.go; the frontend's
//     are Vitest files named *.test.ts / *.test.tsx, which vite build does not
//     emit. Excluding them keeps this rule agreeing with the Core's, and with
//     core/resolve-build-time.sh.
func coversWebInput(relative string) bool {
	if relative == "web/backend/dist" || strings.HasPrefix(relative, "web/backend/dist/") {
		return false
	}
	name := path.Base(relative)
	switch {
	case strings.HasSuffix(name, "_test.go"),
		strings.HasSuffix(name, ".test.ts"),
		strings.HasSuffix(name, ".test.tsx"):
		return false
	}
	return true
}

func hashFile(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	digest := sha256.New()
	if _, err := io.Copy(digest, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

// Stamped is the fingerprint of the Core source this binary was built from.
//
// It is set at link time by the canonical build:
//
//	-X github.com/sipeed/picoclaw/pkg/coresource.Stamped=<fingerprint>
//
// An empty value means the binary was not built through
// core/build-android-arm64.sh, which is itself worth knowing: the test gate
// treats an unstamped Core exactly like a stale one, because neither can be
// shown to match the source in the working tree.
var Stamped string

// Describe names the Core source this binary was built from, for the startup
// diagnostics. It also keeps Stamped referenced by live code: the linker drops
// an unused variable, and a dropped variable takes the -X value with it.
func Describe() string {
	if Stamped == "" {
		return "unstamped"
	}
	return Stamped
}

// StagedCoreMatches reports whether a built Core carries fingerprint.
//
// The fingerprint is a plain string in the binary's data, so containment is the
// whole check: a Core built from this source has it, and one built from any
// other source, or built outside the canonical script, does not.
func StagedCoreMatches(core []byte, fingerprint string) bool {
	if len(fingerprint) != 64 {
		return false
	}
	return bytes.Contains(core, []byte(fingerprint))
}
